# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb01bff8273f38dbfe8ea38346c3be1805b42608ab44be815b880dc92da1e5e73f7f40470658cdb84732593d8eafdbba70ab010bba3b49c9260b765ca93fa3d

test:
  secret_key_base: 1c11af936dac147a0ba807795361f14d3d55da5c41b436b85b73b25ec011f1bc61b7dffebb11f5375bd4abad299fd0f4c7d0f9c5a68df0b767f0473cb0412451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
