---
:concurrency: 3
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

staging:
  :concurrency: 15

production:
  :concurrency: 25

:queues:
  - [default, 2]
  - [mailers, 5]
  - [fast, 5]
  - low
